name: build

on:
  push:
    branches:
      - 'master'
    tags:
      - v*.*.*

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
       name: Docker meta
       id: meta
       uses: docker/metadata-action@v4
       with:
         # list of Docker images to use as base name for tags
         images: |
           leg100/squid
         # generate Docker tags based on the following events/attributes
         tags: |
           type=schedule
           type=ref,event=branch
           type=ref,event=pr
           type=semver,pattern={{version}}
           type=semver,pattern={{major}}.{{minor}}
           type=semver,pattern={{major}}
           type=sha
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build, and push if tagged
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          push: ${{ startsWith(github.ref, 'refs/tags/v') }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

